"""empty message

Revision ID: 15ed16a907c1
Revises: fbad58a99b7b
Create Date: 2024-07-06 19:17:52.072486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ed16a907c1'
down_revision: Union[str, None] = 'fbad58a99b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('last_drop', sa.DateTime(), nullable=True),
                    sa.Column('last_grab', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_foreign_key(op.f('fk_cards_user_id_users'), 'cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cards_user_id_users'), 'cards', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
