"""Initial database

Revision ID: 4dff1f136a47
Revises:
Create Date: 2025-01-18 15:17:46.192480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dff1f136a47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames')),
                    sa.UniqueConstraint('image', name=op.f('uq_frames_image')),
                    sa.UniqueConstraint('name', name=op.f('uq_frames_name'))
                    )
    op.create_table('medias',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('anilist', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_medias')),
                    sa.UniqueConstraint('anilist', name=op.f('uq_medias_anilist'))
                    )
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('last_drop', sa.DateTime(), nullable=True),
                    sa.Column('last_grab', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_table('characters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('anilist', sa.Integer(), nullable=True),
                    sa.Column('media_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name=op.f('fk_characters_media_id_medias')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters')),
                    sa.UniqueConstraint('anilist', name=op.f('uq_characters_anilist'))
                    )
    op.create_table('aliases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('is_spoiler', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_aliases_character_id_characters')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases')),
                    sa.UniqueConstraint('character_id', 'name', name=op.f('uq_aliases_character_id'))
                    )
    op.create_table('editions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('num', sa.Integer(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_editions_character_id_characters')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_editions')),
                    sa.UniqueConstraint('character_id', 'num', name=op.f('uq_editions_character_id'))
                    )
    op.create_table('cards',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('edition_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('frame_id', sa.Integer(), nullable=True),
                    sa.Column('alias_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('grabbed_by', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['alias_id'], ['aliases.id'], name=op.f('fk_cards_alias_id_aliases')),
                    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], name=op.f('fk_cards_edition_id_editions')),
                    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], name=op.f('fk_cards_frame_id_frames')),
                    sa.ForeignKeyConstraint(['grabbed_by'], ['users.id'], name=op.f('fk_cards_grabbed_by_users')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cards_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('editions')
    op.drop_table('aliases')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('medias')
    op.drop_table('frames')
    # ### end Alembic commands ###
