"""empty message

Revision ID: 6afbe09379d9
Revises: 9b899bbc5c65
Create Date: 2024-07-22 01:25:13.147443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afbe09379d9'
down_revision: Union[str, None] = '9b899bbc5c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('is_spoiler', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_aliases_character_id_characters')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases')),
                    sa.UniqueConstraint('character_id', 'name', name=op.f('uq_aliases_character_id'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    # ### end Alembic commands ###
