"""Add character favourites

Revision ID: af630c8e4deb
Revises: bf999bef7299
Create Date: 2025-05-02 22:00:55.116105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af630c8e4deb"
down_revision: Union[str, None] = "bf999bef7299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("favourites", sa.Integer(), nullable=False, server_default="0")
    )

    op.alter_column("characters", "favourites", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "favourites")
    # ### end Alembic commands ###
