"""Add card tags

Revision ID: bf999bef7299
Revises: 4dff1f136a47
Create Date: 2025-01-21 22:10:45.990340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf999bef7299'
down_revision: Union[str, None] = '4dff1f136a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('emoji', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
                    sa.UniqueConstraint('emoji', 'user_id', name=op.f('uq_tags_emoji')),
                    sa.UniqueConstraint('name', 'user_id', name=op.f('uq_tags_name'))
                    )
    op.add_column('cards', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_cards_tag_id_tags'), 'cards', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cards_tag_id_tags'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
