"""empty message

Revision ID: f596083ad9b5
Revises: 418bd0fa4cc9
Create Date: 2024-07-11 18:53:59.049228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f596083ad9b5'
down_revision: Union[str, None] = '418bd0fa4cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames')),
                    sa.UniqueConstraint('image', name=op.f('uq_frames_image')),
                    sa.UniqueConstraint('name', name=op.f('uq_frames_name'))
                    )
    op.add_column('cards', sa.Column('frame_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_cards_frame_id_frames'), 'cards', 'frames', ['frame_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cards_frame_id_frames'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'frame_id')
    op.drop_table('frames')
    # ### end Alembic commands ###
