"""empty message

Revision ID: fa708a3ec141
Revises: f596083ad9b5
Create Date: 2024-07-16 16:30:06.545220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa708a3ec141'
down_revision: Union[str, None] = 'f596083ad9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_characters_anilist'), 'characters', ['anilist'])
    op.create_unique_constraint(op.f('uq_medias_anilist'), 'medias', ['anilist'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_medias_anilist'), 'medias', type_='unique')
    op.drop_constraint(op.f('uq_characters_anilist'), 'characters', type_='unique')
    # ### end Alembic commands ###
