"""empty message

Revision ID: fbad58a99b7b
Revises: f380a99b72cb
Create Date: 2024-07-06 18:00:53.209814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbad58a99b7b'
down_revision: Union[str, None] = 'f380a99b72cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
                    sa.Column('card_id', sa.Integer(), nullable=False),
                    sa.Column('edition_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], name=op.f('fk_cards_edition_id_editions')),
                    sa.PrimaryKeyConstraint('card_id', name=op.f('pk_cards'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
