"""empty message

Revision ID: fd884fd43dca
Revises: 6afbe09379d9
Create Date: 2024-07-22 21:06:47.484247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd884fd43dca'
down_revision: Union[str, None] = '6afbe09379d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('alias_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_cards_alias_id_aliases'), 'cards', 'aliases', ['alias_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cards_alias_id_aliases'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'alias_id')
    # ### end Alembic commands ###
