name: Deploy

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server or Storage Box
        run: |
          rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/ayase
          ssh -i $HOME/.ssh/id_ed25519 -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ayase && docker compose --env-file .env.prod up --build -d"
